config/routes.rb
Cats99::Application.routes.draw do

  resources :cats
  resources :cat_rental_requests do
    member do
      put "approve"
      put "deny"
    end
  end

  resources :users, only: [:new, :create]
  resource :sessions #exclude extras if not needed

  root :to => 'cats#index'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(black brown white orange)
  SEX = ['','M', 'F']
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id

  validates :age, :birth_date, :color, :name, :sex, :user_id, presence: true
  validates :age, numericality: true
  validates :color, inclusion: { in: %w(black brown white orange),
    message: "%{value} is not a valid color" }
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a valid sex" }


  has_many(
    :cat_rental_requests,
    class_name: "CatRentalRequest",
    primary_key: :id,
    foreign_key: :cat_id
  )

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :end_date, :start_date, :status

  before_validation(on: :create) { self.status ||= "PENDING" }

  validates :cat_id, :end_date, :start_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED),
    message: "%{value} is not a valid status" }
  validate :overlapping_approved_requests

  belongs_to(
    :cat,
    dependent: :destroy,
    class_name: "Cat",
    primary_key: :id,
    foreign_key: :cat_id
  )

  def overlapping_requests
    new_start = self.start_date
    new_end   = self.end_date

    CatRentalRequest.where("id != ? AND cat_id = ? AND NOT (start_date >= ? OR end_date <= ?)", self.id, self.cat_id, new_end, new_start)

  end

  def overlapping_approved_requests
    return if self.status != "APPROVED"
    unless self.overlapping_requests.where(:status == "APPROVED").empty?
      errors[:base] << "Overlapping Approved Requests"
    end
  end

  def approve!
    self.status = "APPROVED"
    if self.save
      self.overlapping_pending_requests.each do |request|
        request.deny!
      end
    end
  end

  def overlapping_pending_requests
    self.overlapping_requests.where(:status == "PENDING")
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == "PENDING"
  end


end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :token, :user_id

  validates :user_id, :token, presence: true

  def self.create_session(user)
    Session.create!(user_id: user.id, token: Session.generate_new_token!)
  end

  def self.generate_new_token!
    SecureRandom::urlsafe_base64(16)
  end

  belongs_to(
  :user,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :user_name, :password
  attr_reader :password

  validates :password_digest, presence: { :message => "Password can't be blank" }
  validates :user_name, presence: true
  # validates :session_token, presence: true
  validates :user_name, uniqueness: true

  # before_validation(on: :create) { self.session_token ||= reset_session_token! }

  has_many(
    :cats,
    class_name: "Cat",
    foreign_key: :user_id,
    primary_key: :id
  )

  has_many(
  :sessions,
  class_name: "Session",
  foreign_key: :user_id,
  primary_key: :id
  )

  def self.find_by_credentials(user_name, password)
    possible_user = User.find_by_user_name(user_name)
    if possible_user.is_password?(password)
      return possible_user
    end
    nil
  end

  # def reset_session_token!
#     self.session_token = SecureRandom::urlsafe_base64(16)
#   end

  def password=(password)
    @password = password
    unless password.strip == ""
      self.password_digest = BCrypt::Password.create(password)
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  before_filter :rental_require_current_user!, :except => [:create, :new]

  def new
    @all_cats = Cat.all
    render :new
  end

  def create
    new_request = CatRentalRequest.new(params[:cat_rental_request])
    if new_request.save
      redirect_to cat_url(new_request.cat_id)
    else
      render :json => new_request.errors, :status => :unprocessable_entity
    end
  end

  def approve
    rental_request = CatRentalRequest.find(params[:id])
    rental_request.approve!
    redirect_to rental_request.cat
  end

  def deny
    rental_request = CatRentalRequest.find(params[:id])
    rental_request.deny!
    redirect_to rental_request.cat
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :cat_require_current_user!, :only => [:edit, :update, :destroy]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new()
    render :new
  end

  def create
    new_cat = current_user.cats.new(params[:cat])
    if new_cat.save
      redirect_to new_cat
    else
      render :json => new_cat.errors, :status => :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    Cat.update(params[:id],params[:cat])
    redirect_to Cat.find(params[:id])
  end

  def destroy
    Cat.destroy(params[:id])
    redirect_to cats_url
  end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create

    login_user!
  end

  def destroy
    logout_current_user!
    redirect_to new_sessions_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    new_user = User.new(params[:user])
    if new_user.save
      login_user!
    else
      render text: new_user.errors
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user=(user)
    @current_user = user
    new_session = Session.create_session(user)
    session[:session_token] = new_session.token
  end

  def current_user
    secret_token = session[:session_token]
    return nil if secret_token.nil?
    session = Session.find_by_token(secret_token)
    if session
      @current_user ||= session.user
    end
  end

  def logout_current_user!
    current_session = Session.find_by_token(session[:session_token])
    Session.destroy(current_session.id)

    # current_user.reset_session_token!
#     current_user.save
#     session[:session_token] = nil #delete row form session table instead
  end

  def login_user!
    user =  User.find_by_credentials(get_user_name, get_password)
    unless user.nil?
      self.current_user = user
      redirect_to cats_url
    else
      render :json => "Credentials were wrong"
    end
  end

  def get_password
    params[:user][:password]
  end

  def get_user_name
    params[:user][:user_name]
  end

  def cat_require_current_user!
    owner_id = Cat.find(params[:id]).user_id
    require_current_user(owner_id)
  end

  def rental_require_current_user!
    owner_id = CatRentalRequest.find(params[:id]).cat.user_id
    require_current_user(owner_id)
  end

  private

    def require_current_user(owner_id)
      redirect_to new_sessions_url unless current_user.id == owner_id
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <strong>99 Cats | New Cat Rental Request </strong>
    </title>
  </head>

  <body>

    <form action="<%= cat_rental_requests_url %>" method="post">

      <%= render "/shared/token_check" %>
      <!-- :cat_id, :end_date, :start_date, :status -->
      <label> Select Cat
        <select name="cat_rental_request[cat_id]">
          <option value=  > </option >
          <% @all_cats.each do |cat| %>
          <option value=<%= cat.id %>> <%= cat.name %> </option >
          <% end %>
        </select>
      </label>
      <br>

      <label> Start Date
      <input type="date" name="cat_rental_request[start_date]">
      </label>
      <br>

      <label> End Date
      <input type="date" name="cat_rental_request[end_date]">
      </label>
      <br>

      <input type="submit" value="Submit Request">
    </form>
  </body>

</html>

app/views/cats/_form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <strong>99 Cats | <%= @cat.persisted? ? "Update" : "New" %> </strong>
    </title>
  </head>

  <body>

    <form action="<%= @cat.persisted? ? cat_url(@cat.id) : new_cat_url %>" method="post">
      <%= render "/shared/token_check" %>

      <%= "<input type='hidden' name='_method' value='PUT'>".html_safe if @cat.persisted? %>

      <label>Name
      <input type="text" name="cat[name]" value="<%= @cat.name %>">
      </label>
      <br>

      <label>Age
      <input type="text" name="cat[age]" value="<%= @cat.age %>">
      </label>
      <br>

      <label for="cat_color">Color</label>
      <br>
      <% Cat::COLORS.each do |color| %>
      <input type="radio" name="cat[color]" id="cat_color_<%= color %>"
      value="<%= color %>" <%= "checked" if @cat.color == color %>>
      <label for="cat_color_<%= color %>"><%= color.capitalize %></label>
      <br>
      <% end %>

      <label for="cat_sex">Sex</label>

        <select name="cat[sex]" id="cat_sex">
          <% Cat::SEX.each do |sex| %>
          <option value=<%= sex %> <%= "selected" if @cat.sex == sex %>> <%= sex %> </option >
          <% end %>
        </select>
        <br>

      <label for="cat_birth_date">Birth Date
      <input type="date" name="cat[birth_date]" value=<%= @cat.birth_date %>>
      </label>
      <br>

      <input type="submit" value=<%= @cat.persisted? ? "Update Cat" : "Create Cat" %>>
    </form>
  </body>

</html>

app/views/cats/edit.html.erb
<%= render "form" %>

app/views/cats/index.html.erb
<% if current_user.nil? %>
  <ul>
    <li><%= button_to "Sign In", new_sessions_url, method: :get %></li>
    <li><%= button_to "Sign Up", new_user_url, method: :get %></li>
  </ul>
<% end %>

<br>
<br>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= link_to cat.name, cat_url(cat.id) %>
    </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<%= render "form" %>

app/views/cats/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <strong> <%= @cat.name %> </strong>
    </title>
  </head>

  <body>

    <table>
      <thead> <%=@cat.name%>'s Attributes </thead>
      <th>Age</th>
      <th>Birth Date</th>
      <th>Color</th>
      <th>Sex</th>
      <tr>
        <td> <%= @cat.age %> </td>
        <td> <%= @cat.birth_date %> </td>
        <td> <%= @cat.color %> </td>
        <td> <%= @cat.sex %> </td>
      </tr>
    </table>

    <br>

    <table>
      <thead> <%=@cat.name%>'s Requests </thead>
      <th colspan=2>Dates</th>

      <% @cat.cat_rental_requests.order(:start_date).each do |request| %>
        <tr>
          <td> <%= request.start_date %> </td>
          <td> <%= request.end_date %> </td>

          <% if request.pending? && current_user && @cat.user_id == current_user.id %>
            <td> <%= button_to "Approve", approve_cat_rental_request_url(request.id), :method => :put %></td>
            <td> <%= button_to "Deny", deny_cat_rental_request_url(request.id), :method => :put %></td>
          <% end %>

        </tr>
      <% end %>

    </table>

  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul>
    <% if current_user %>
      <li>Logged in as: <%= current_user.user_name %></li>
      <li><%= button_to "Logout", sessions_url, :method => :delete %></li>
    <% end%>
  <ul>

<%= yield %>

</body>
</html>

app/views/shared/_name_pw_form.html.erb
<% source =  params[:controller]%>

<h1> <%= source == "users" ? "Sign Up" : "Sign In" %> </h1>

<form action="<%= source == "users" ? users_url : sessions_url %>" method="post">

  <%= render "/shared/token_check" %>

  <label>User Name
    <input type="text" name="user[user_name]" >
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>

<input type="submit" value="<%=source == "users" ? "Sign Up" : "Sign In" %>">

app/views/shared/_token_check.html.erb
<input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

app/views/users/new.html.erb
<%= render "shared/name_pw_form" %>